language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
  - travis_retry pip install -U -r dev-requirements.txt
  - travis_retry pip install -U .

script: py.test
